// // What is NPM in React and What is the role of node_modules folder?
// NPM (Node Package Manager) is a package manager for JavaScript that is commonly used in React development. It allows developers to easily install, manage, and share libraries and dependencies needed for their projects. NPM comes bundled with Node.js, which is a JavaScript runtime environment.
// The role of the node_modules folder is to store all the installed packages and their dependencies for a React project. When you run the command `npm install <package-name>`, NPM downloads the specified package and its dependencies from the NPM registry and places them in the node_modules folder. This folder is essential for the project to function correctly, as it contains all the code required for the application to run.
// In summary, NPM is a tool that helps manage JavaScript packages, and the node_modules folder is where those packages are stored within a React project. 

// What is the role of package.json and package-lock.json files in a React project?
// The package.json file is a crucial component of a React project that serves several important roles:
// 1. Project Metadata: It contains metadata about the project, such as its name, version, description, author, and license.
// 2. Dependencies Management: It lists all the dependencies and devDependencies required for the project to run. This allows developers to easily install and manage the libraries needed for their application.
// 3. Scripts: It defines custom scripts that can be run using NPM commands. For example, you can define scripts for starting the development server, building the project, running tests, etc.
// 4. Configuration: It can also include configuration settings for various tools and libraries used in the project.
// The package-lock.json file, on the other hand, is automatically generated when you install packages using NPM. Its primary roles are:
// 1. Dependency Tree: It records the exact versions of all installed packages and their dependencies, ensuring that the same versions are used when the project is installed on different machines.
// 2. Consistency: It helps maintain consistency across different environments by locking the dependency versions, preventing potential issues caused by version mismatches.
// 3. Performance: It speeds up the installation process by allowing NPM to quickly resolve and install the required packages based on the locked versions.
// In summary, package.json manages project metadata, dependencies, and scripts, while package-lock.json ensures consistent and reliable installations of those dependencies across different environments. 

// What is the role of public folder in a React project?
// The public folder in a React project serves as the location for static assets that need to be directly accessible by the web browser. These assets can include HTML files, images, fonts, icons, and other files that do not require processing by the React build system.

// What is the role of src folder in a React project?
// The src (source) folder in a React project is where the main application code resides. It contains all the JavaScript and JSX files that define the components, logic, and styles of the React application. This folder is the primary workspace for developers to build and organize their React components and application structure.

// What is the role of index.html file in a React project?
// The index.html file in a React project serves as the main HTML template for the application. It is located in the public folder and provides the basic structure of the web page. This file typically includes a root div element (often with the id "root") where the React application will be mounted. When the React app is built and served, the content generated by React components is injected into this root element, allowing the dynamic rendering of the application within the static HTML structure.

// What is the role of index.js file in a React project?
// The index.js file in a React project serves as the entry point for the application. It is responsible for rendering the root React component (usually App.js) into the DOM. This file typically imports necessary dependencies, sets up the React application, and mounts it to a specific HTML element (often with the id "root") in the public/index.html file. Essentially, index.js initializes the React application and connects it to the web page.

// What is the role of App.js file in a React project?
// The App.js file in a React project serves as the main component that acts as the root of the component hierarchy. It is typically where the overall structure and layout of the application are defined. The App.js file often contains other components, manages state, and handles routing if applicable. It serves as the central point for organizing and rendering the various parts of the React application.


function Parent() {
    return (
    <div>
        <ChildProp msg="Hello from Parent Component!" />
    </div>
    );

}

function ChildProp(props) {
    return (
        <>
          <GreatChildProp msg={props} />
          </>
    );
}

function GreatChildProp(props) {
    return (
        <div>
            <h2>{props.msg}</h2>
        </div>
    );
}

export {Parent, ChildProp, GreatChildProp};
// What is props drilling in React?
// Props drilling in React refers to the process of passing data from a parent component to a deeply nested child component through multiple layers of intermediate components. 



import React, { useEffect } from "react";
import { BrowserRouter as Router, Routes, Route, Link } from "react-router-dom";

class ParentComponent extends React.Component {

    render() {
        return (
            <div>
                <ChildComponent data="Data from Parent" />
            </div>
        );
    }

}

class ChildComponent extends React.Component {
    render() {
        return (
            <div>   
               <h1> {this.props.data} </h1>
            </div>
        );
    }
}
export {ParentComponent, ChildComponent};

// What is state in React?
// State in React is a built-in object that allows components to manage and track dynamic data that can change over time. It enables components to respond to user interactions, update the UI, and maintain the current status of the application. State is mutable, meaning it can be modified using the setState() method in class components or the useState() hook in functional components. When the state changes, React re-renders the component to reflect the updated data in the UI.


// How to implement routing in Reaact ?
    // function Home() {
    //     return <h2>Home Page</h2>;
    // }
    // function About() {
    //     return <h2>About Page</h2>;
    // }
    // function Contact() {
    //     return <h2>Contact Page</h2>;
    // }

    // function AppRouter() {
    //     return (
    //         <Router>
    //             <nav style={{ marginBottom: 12 }}>
    //                 <Link to="/">Home</Link> | <Link to="/about">About</Link> |{" "}
    //                 <Link to="/contact">Contact</Link>
    //             </nav>

    //             <Routes>
    //                 <Route path="/" element={<Home />} />
    //                 <Route path="/about" element={<About />} />
    //                 <Route path="/contact" element={<Contact />} />
    //             </Routes>
    //         </Router>
    //     );
    // }

    // export default AppRouter;



    import { useEffect } from "react"

    function fetchUsers() {
      console.log("user")
    }
    
    function App() {
      useEffect(() => {
        fetchUsers()
      }, [])
    
      return (
        <>
          <h1>Data fetching</h1>
        </>
      )
    }
    
    export default App
    
